### PR TITLE
fix: Changed styling on feedback buttons

### PR DESCRIPTION
**Pull request by peloycosta**
Added a hover color change to the feedback buttons consistent with the color on the top right version selector.
Changed the cursor icon to reflect being clickable.
Adjusted the padding slightly to roughly center the weight of the icon + text visually.

### CODE REVIEW

**Comment by pauloribeiro-codacy** [comment]
Right now, on hover, the background color of the buttons seems to be the same as the background of the page. :thinking: Was this the intended effect?

Peek 2021-01-05 15-38

**Review by pauloribeiro-codacy — COMMENTED** [review]
Right now, on hover, the background color of the buttons is very similar to the background of the page. :thinking: Was this the intended effect?

Peek 2021-01-05 15-38

**Comment by peloycosta** [comment]
> Right now, on hover, the background color of the buttons is very similar to the background of the page. 🤔 Was this the intended effect?

My bad, I missed that we didn't have all colors on the CSS vars. I've added them now.

**Comment by pauloribeiro-codacy** [comment]
> > Right now, on hover, the background color of the buttons is very similar to the background of the page. thinking Was this the intended effect?
> 
> My bad, I missed that we didn't have all colors on the CSS vars. I've added them now.

Looks perfect now! :ok_hand: :star_struck: 

Peek 2021-01-05 17-47

**Review by pauloribeiro-codacy — APPROVED** [review]

**Pull request merged**
